version: '3.8'

services:
  local-maxgpt:
    build:
      context: .
      dockerfile: Dockerfile.maxgpt
    image: local-maxgpt-branded:latest
    container_name: local-maxgpt-branded
    restart: unless-stopped
    ports:
      - "8080:8080"  # API and Web UI
    environment:
      - DEBUG=false
      - MODELS_PATH=/models
      - THREADS=8
      - CONTEXT_SIZE=2048
      - GPU_LAYERS=-1
      - LOCALAI_GALLERIES='[{"name":"maxgpt","url":"https://raw.githubusercontent.com/yosiwizman/local-maxgpt/main/models/"}]'
    volumes:
      - ./models:/models
      - ./data:/data
      - ./images:/tmp/generated/images/
      - ./converted_models:/converted_models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
